### ISSUE TITLE
Website checklist issue example

### ISSUE THREAD

**Issue by andreasantonsson** [significantbit/prelaunch-website-checklist#1]
[significantbit / prelaunch-website-checklist](https://github.com/significantbit/prelaunch-website-checklist)

- [ ] Language
- [ ] Metadata
    - [ ] Format `<title>`
    - [ ] Open graph
- [ ] Favicons
- [ ] Accessibility
  - [ ] Skip link
  - [ ] Aria landmark roles
  - [ ] Run tests with WAVE Evaluation Tool
- [ ] Error pages
- [ ] Cookies
- [ ] Markup Validation
- [ ] Run through a [web.dev measure](https://web.dev/measure/)
- [ ] Tracking codes (Google Analytics, Facebook Pixels etc)
- [ ] Performance
  - [ ] Run tests on [PageSpeed Insights](http://developers.google.com/speed/pagespeed/insights/)
  - [ ] Run tests on [Web Page Performance Test](http://www.webpagetest.org/)
- [ ] SSL/HTTPS
- [ ] Security headers
- [ ] Robots.txt
- [ ] Documentation
